all: 01-intro 02-web 03-rev 04-pwn 05-crypto 06-forensics 07-misc 08-outro

MARP_ARGS = --allow-local-files --theme style.css --pdf

01-intro:
	marp $(MARP_ARGS) 01-intro.md
02-web:
	marp $(MARP_ARGS) 02-web.md
03-rev:
	marp $(MARP_ARGS) 03-rev.md
04-pwn:
	marp $(MARP_ARGS) 04-pwn.md
05-crypto:
	marp $(MARP_ARGS) 05-crypto.md
06-forensics:
	marp $(MARP_ARGS) 06-forensics.md
07-misc:
	marp $(MARP_ARGS) 07-misc.md
08-outro:
	marp $(MARP_ARGS) 08-outro.md
